[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "boomtranscript"
version = "0.1.0"
description = "Modern Discord transcript exporter for discord.py"
authors = [
    {name = "MateoBD"}
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "discord.py>=2.4.0"
]
